[package]
name = "haxe-extension"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
flate2 = { version = "1", default-features = false, features = [
    "rust_backend",
] }
zip = { version = "2", default-features = false, features = ["deflate"] }
zed_extension_api = "0.2.0"
