id = "haxe"
name = "Haxe"
version = "0.4.0"
schema_version = 1
authors = ["Frixuu <kontakt@lukasz.xyz>"]
description = "Language server and syntax highlighting support for the Haxe programming language."
repository = "https://github.com/Frixuu/Zed-Haxe"

[grammars.haxe]
repository = "https://github.com/tong/tree-sitter-haxe"
commit = "7bf6ca91398a7a3b5a3db4c727b17c15cb370baf"

[grammars.hxml]
repository = "https://github.com/Frixuu/tree-sitter-hxml"
commit = "a1e005fdaf2a50e013ed073a029039fa0a6188e3"

[language_servers.haxe-language-server]
name = "Haxe Language Server"
languages = ["Haxe", "HXML"]
