id = "haxe"
name = "Haxe language support"
version = "0.1.2"
schema_version = 1
authors = ["Frixuu <kontakt@lukasz.xyz>"]
description = "Unofficial Haxe programming language support."
repository = "https://github.com/Frixuu/Zed-Haxe"

[grammars.haxe]
repository = "https://github.com/vantreeseba/tree-sitter-haxe"
commit = "12e814cd9b0656b0eaa3e04b0036b3b6625cc0d7"

[language_servers.haxe-language-server]
name = "Haxe Language Server"
language = "Haxe"
